# Generated by Django 6.0.3 on 2026-03-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColdStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.FloatField(blank=True, help_text='Capacity in MT', null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('project_cost', models.FloatField(blank=True, null=True)),
                ('grant_released', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('crop', models.CharField(max_length=100)),
                ('season', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('production', models.FloatField(blank=True, null=True)),
                ('year', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ministry', models.CharField(default='Ministry of Food Processing Industries', max_length=255)),
                ('eligibility', models.TextField()),
                ('benefits', models.TextField()),
                ('application_process', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
